filter:
    paths:
        - src/*

build:
    environment:
        php: 7.1

    project_setup:
        before:
            - 'cp .env.dist .env'
            - 'bash ./bin/setup.bash'
    tests:
        override:
            -
                command: './vendor/bin/phpspec run -f progress -c phpspec-ci.yml'
                coverage:
                    file: 'coverage.xml'
                    format: 'php-clover'
            -
                command: './bin/phpunit'
                coverage:
                    file: 'tests/_reports/logs/clover.xml'
                    format: 'clover'
tools:
    php_cs_fixer:
        config: { level: psr2 }

checks:
    php:
        code_rating: true
        duplication: true
