filter:
    paths:
        - Api/src/*

build:
    environment:
        php: 7.1

    project_setup:
        before:
            - 'cd Api'
            - 'composer install'
    tests:
        override:
            -
                command: './vendor/bin/phpspec run -f progress -c phpspec-ci.yml'
                coverage:
                    file: 'Api/coverage.xml'
                    format: 'php-clover'
            -
                command: './bin/phpunit'

tools:
    php_cs_fixer:
        config: { level: psr2 }
