filter:
    paths:
        - src/*

build:
    environment:
        php:
            version: 7.1.0

    project_setup:
        before:
            - 'cd Api'
            - 'composer install --prefer-dist'

    tests:
        override:
            -
                command: './bin/phpspec run -f progress -c ./phpspec-ci.yml'
                coverage:
                    file: './Api/coverage.xml'
                    format: 'php-clover'

tools:
    php_cs_fixer:
        config: { level: psr2 }
