filter:
    paths:
        - Api/src/*

build:
    tests:
        override:
            -
                command: './Api/bin/phpspec run -f progress -c ./Api/phpspec-ci.yml'
                coverage:
                    file: 'coverage.clover'
                    format: 'php-clover'
