filter:
    paths:
        - src/*

build:
    environment:
        php:
            version: 7.1.0
    tests:
        override:
            -
                command: 'cd Api; ./bin/phpspec run -f progress -c ./phpspec-ci.yml'
                coverage:
                    file: './Api/coverage.xml'
                    format: 'php-clover'

tools:
    php_cs_fixer:
        config: { level: psr2 }
