filter:
    paths:
        - Api/src/*

build:
    project_setup:
        before:
            - "cd Api"
    tests:
        override:
            -
                command: './bin/phpspec run -f progress -c ./phpspec-ci.yml'
                coverage:
                    file: 'coverage.clover'
                    format: 'php-clover'
