services:
  node:
    build:
      context: .
      target: dev
    volumes:
      - ./:/app
      - ~/.npm:/home/node/.npm
    command: yarn serve
    environment:
      - NODE_ENV=development
    ports:
      - 8080:8080
