parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): 'sqlite:///%kernel.project_dir%/var/shopping.sqlite3'

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_sqlite'
        charset: UTF8
        url: '%env(resolve:DATABASE_URL)%'
