BEGIN TRANSACTION;
insert into categories ("id", "name") values ('1', 'Frais');
insert into categories ("id", "name") values ('2', 'Scolaire');
insert into categories ("id", "name") values ('3', 'Jeux / Jouets');
insert into categories ("id", "name") values ('4', 'Droguerie');
insert into categories ("id", "name") values ('5', 'Condiments');
insert into categories ("id", "name") values ('6', 'Boissons');
insert into categories ("id", "name") values ('7', 'Bricolage');
insert into categories ("id", "name") values ('8', 'Cuisine');
insert into categories ("id", "name") values ('9', 'Légumes');
insert into categories ("id", "name") values ('10', 'Surgelés');
COMMIT;
