#index:
#    path: /
#    controller: App\Controller\DefaultController::index

user_login:
    path: /login
    defaults: { _controller: Jmleroux\JmlShopping\Api\ApiBundle\Controller\TokenController::loginAction }
    methods: [POST]

product_list:
    path: /products
    defaults: { _controller: Jmleroux\JmlShopping\Api\ApiBundle\Controller\ProductController::listAction }
    methods: [GET]

product_view:
    path: /product/{id}
    defaults: { _controller: Jmleroux\JmlShopping\Api\ApiBundle\Controller\ProductController::viewAction }
    methods: [GET]
    requirements:
        id: \w+

product_create:
    path: /product
    defaults: { _controller: Jmleroux\JmlShopping\Api\ApiBundle\Controller\ProductController::createAction }
    methods: [POST]

product_update:
    path: /product/{id}
    defaults: { _controller: Jmleroux\JmlShopping\Api\ApiBundle\Controller\ProductController::updateAction }
    methods: [PUT]

product_delete:
    path: /product/{id}
    defaults: { _controller: Jmleroux\JmlShopping\Api\ApiBundle\Controller\ProductController::deleteAction }
    methods: [DELETE]

product_clear_all:
    path: /products
    defaults: { _controller: Jmleroux\JmlShopping\Api\ApiBundle\Controller\ProductController::truncateAction }
    methods: [DELETE]

category_list:
    path: /categories
    defaults: { _controller: Jmleroux\JmlShopping\Api\ApiBundle\Controller\CategoryController::listAction }
    methods: [GET]
