imports:
    - { resource: parameters.yml }
    - { resource: services.yml }

framework:
    secret: '%secret%'

doctrine:
    dbal:
        driver: 'pdo_sqlite'
        path:   '%db_path%'

security:
    providers:
        jmlshopping:
            id: 'jmlshopping.security.user_provider'

    firewalls:
        login:
            pattern:                        ^/login$
            anonymous:                      true
        main:
            anonymous: ~
            logout: ~
            guard:
                authenticators:
                    - 'jmlshopping.security.token_authenticator'
