# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    encoder.seed: 'def000004df82059ef280997071b2a3b0501164cc8e4bc25d930a4fa7f79f21efabab7a9cd1ba900bedd6020ef916182c5fb463cf123f6d5a14b231318f5dcfc49a99a2a'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Jmleroux\JmlShopping\Api\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Jmleroux\JmlShopping\Api\ApiBundle\Controller\:
        resource: '../src/ApiBundle/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    jmlshopping.category:
        class: Jmleroux\JmlShopping\Api\ApiBundle\Repository\CategoryRepository

    jmlshopping.product:
        class: Jmleroux\JmlShopping\Api\ApiBundle\Repository\ProductRepository
        arguments:
            - '@database_connection'
            - '@jmlshopping.category'

    jmlshopping.user:
        class: Jmleroux\JmlShopping\Api\ApiBundle\UserService
        arguments:
            - '@database_connection'
            - '%encoder.seed%'

    jmlshopping.security.user_provider:
        class: Jmleroux\JmlShopping\Api\ApiBundle\Security\UserProvider
        arguments:
            - '@database_connection'
            - '@jmlshopping.user'

    jmlshopping.security.token_authenticator:
        class: Jmleroux\JmlShopping\Api\ApiBundle\Security\TokenAuthenticator
