version: '3'

services:
  fpm:
    image: jmleroux/fpm:php-7.3
    environment:
      APP_ENV: '${APP_ENV:-prod}'
      COMPOSER_HOME: /home/docker/.composer
    user: "${UID}:${GID}"
    volumes:
      - ./:/srv/jmleroux
      - ~/.composer:/home/docker/.composer
    working_dir: /srv/jmleroux
    networks:
      - jmleroux-network

  nginx:
    image: 'nginx:alpine'
    depends_on:
      - 'fpm'
    volumes:
      - './:/srv/jmleroux:ro'
      - './docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
    networks:
      - jmleroux-network

  node:
    image: node:10
    user: node
    volumes:
      - ./:/srv/jmleroux
    working_dir: /srv/jmleroux
    networks:
      - jmleroux-network

networks:
  jmleroux-network:
